Conv1DNet(
  (layer1): Sequential(
    (0): Conv1d(1, 16, kernel_size=(5,), stride=(1,), padding=(2,))
    (1): ReLU()
    (2): MaxPool1d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
  (layer2): Sequential(
    (0): Conv1d(16, 32, kernel_size=(5,), stride=(1,), padding=(2,))
    (1): ReLU()
    (2): MaxPool1d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
  (fc): Linear(in_features=1568, out_features=10, bias=True)
)
Traceback (most recent call last):
  File "C:\Users\bjark\AppData\Local\Temp\ipykernel_30228\30544962.py", line 13, in model_pipeline
    train(model, train_loader, criterion, optimizer, config)
  File "C:\Users\bjark\AppData\Local\Temp\ipykernel_30228\550994474.py", line 12, in train
    loss = train_batch(images, labels, model, optimizer, criterion)
  File "C:\Users\bjark\AppData\Local\Temp\ipykernel_30228\550994474.py", line 25, in train_batch
    outputs = model(images)
  File "C:\Users\bjark\anaconda3\lib\site-packages\torch\nn\modules\module.py", line 1538, in _call_impl
    result = forward_call(*args, **kwargs)
  File "C:\Users\bjark\AppData\Local\Temp\ipykernel_30228\4164545040.py", line 20, in forward
    out = self.fc(out)
  File "C:\Users\bjark\anaconda3\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\bjark\anaconda3\lib\site-packages\torch\nn\modules\linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (128x6272 and 1568x10)